apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
  namespace: default
spec:
  global:
    site: us5.datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key

  features:
    apm:
      enabled: true

    admissionController:
      enabled: true

    apmInstrumentation:
      enabled: true
      languages:
        java:
          enabled: true